"""
plot_mgg_sculpting.py
=====================
Plots the diphoton invariant mass (m_gg) distribution before and after BDT cut.

Corresponds to Semester Report:
- Section 6: Diphoton Mass Sculpting and Correlation Analysis
- Figure 5: Diphoton invariant mass (m_gg) distribution before and after a BDT
  score cut at 0.7. Distortion of the background shape is visible in the 20-50 GeV region.

Reads directly from the histograms generated by run_bdt_inference.py.
"""

import os
import sys
import argparse
import numpy as np
import uproot
import matplotlib.pyplot as plt

# Ensure config can be found from parent directory or current dir
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from config import (
    MASS_POINTS,
    PROCESS_NAMES,
    MGG_RANGE,
    find_data_file
)

# Colors matching CMS paper conventions
PROCESS_COLORS = {
    0: "#8B4513",  # TTG1Jets: brown
    1: "#1f77b4",  # TTto2L2Nu: dark blue
    2: "#aec7e8",  # TTtoLNu2Q: light blue
    3: "#2ca02c",  # WGtoLNuG: green
    4: "#ff7f0e",  # DYto2Mu50: orange
    5: "#d62728",  # DYto2E50: red
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot diphoton mass sculpting before and after BDT cuts."
    )
    parser.add_argument(
        "--infile",
        default="plots/histograms/histograms_physwgt.root",
        help="Input ROOT histogram file"
    )
    parser.add_argument(
        "--outdir",
        default="plots/mgg",
        help="Output directory for plots"
    )
    parser.add_argument(
        "--sig_masses",
        default="20,40,60",
        help="Comma-separated signal mass points to overlay (default: 20,40,60)"
    )
    parser.add_argument(
        "--bdt_cut",
        type=float,
        default=0.7,
        help="BDT cut value label"
    )
    return parser.parse_args()


def plot_stacked_canvas(ax, h_bkg_dict, h_sig_dict, bins, title, is_postcut=False):
    centers = (bins[:-1] + bins[1:]) / 2.0
    width = bins[1] - bins[0]

    # Stack backgrounds in order: DY (top), WG, TTtoLNu2Q, TTto2L2Nu, TTG1Jets (bottom)
    order = [0, 1, 2, 3, 4, 5]
    bottom = np.zeros(len(centers))

    for pid in order:
        if pid in h_bkg_dict:
            counts = h_bkg_dict[pid]
            pname = PROCESS_NAMES.get(pid, f"PID {pid}")
            color = PROCESS_COLORS.get(pid, "gray")
            ax.bar(centers, counts, width=width, bottom=bottom, color=color, label=pname, edgecolor="none")
            bottom += counts

    # Total background uncertainty band (Poisson sqrt)
    ax.bar(centers, 2 * np.sqrt(np.maximum(bottom, 0)), width=width, bottom=bottom - np.sqrt(np.maximum(bottom, 0)),
           color="gray", alpha=0.3, hatch="//", label="Bkg Stat. Unc.")

    # Overlay signal mass points
    sig_colors = ["black", "darkviolet", "teal", "magenta"]
    for i, (mp, sig_counts) in enumerate(h_sig_dict.items()):
        c = sig_colors[i % len(sig_colors)]
        scale_label = ""
        ax.step(bins, np.append(sig_counts, sig_counts[-1]), where="post", color=c, linewidth=1.8,
                label=f"m_a = {mp} GeV {scale_label}")

    ax.set_xlabel(r"$m_{\gamma\gamma}$ [GeV]", fontsize=12)
    ax.set_ylabel(f"Events / {width:.1f} GeV", fontsize=12)
    ax.set_title(title, fontsize=13)
    ax.set_xlim(MGG_RANGE[0], MGG_RANGE[1])
    ax.set_ylim(0, max(bottom.max() * 1.35, 1.0))
    ax.legend(loc="upper right", frameon=True, fontsize=9, ncol=2)
    ax.grid(True, linestyle=":", alpha=0.5)


def main():
    args = parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    in_file = find_data_file(args.infile)
    print(f"[Plotting Sculpting] Reading histograms from: {in_file}")

    sig_mps = [int(m.strip()) for m in args.sig_masses.split(",")]

    with uproot.open(in_file) as f_in:
        # 1. Plot Pre-cut (Figure 5a)
        bkg_pre = {}
        bins = None
        for pid in [0, 1, 2, 3, 4, 5]:
            k = f"mgg_bkg_pid{pid}_precut"
            if k in f_in:
                counts, edges = f_in[k].to_numpy()
                bkg_pre[pid] = counts
                bins = edges

        sig_pre = {}
        for mp in sig_mps:
            k = f"mgg_sig_m{mp}_precut"
            if k in f_in:
                counts, edges = f_in[k].to_numpy()
                sig_pre[mp] = counts

        fig, ax = plt.subplots(figsize=(8, 6))
        plot_stacked_canvas(ax, bkg_pre, sig_pre, bins, "(a) Before BDT cut")
        plt.tight_layout()
        out_pre = os.path.join(args.outdir, "mgg_precut.png")
        plt.savefig(out_pre, dpi=300)
        plt.savefig(os.path.join(args.outdir, "mgg_precut.pdf"))
        plt.close()
        print(f"[Figure 5a Generated] Saved {out_pre}")

        # 2. Plot Post-cut at m_a = 40 GeV hypothesis (Figure 5b)
        ref_mp = 40
        bkg_post = {}
        for pid in [0, 1, 2, 3, 4, 5]:
            k = f"mgg_bkg_pid{pid}_m{ref_mp}_postcut"
            if k in f_in:
                counts, edges = f_in[k].to_numpy()
                bkg_post[pid] = counts

        sig_post = {}
        if f"mgg_sig_m{ref_mp}_postcut" in f_in:
            sig_post[ref_mp], _ = f_in[f"mgg_sig_m{ref_mp}_postcut"].to_numpy()

        fig, ax = plt.subplots(figsize=(8, 6))
        plot_stacked_canvas(ax, bkg_post, sig_post, bins, f"(b) After BDT cut > {args.bdt_cut} (m_a = {ref_mp} GeV hypothesis)", is_postcut=True)
        plt.tight_layout()
        out_post = os.path.join(args.outdir, f"mgg_postcut_m{ref_mp}.png")
        plt.savefig(out_post, dpi=300)
        plt.savefig(os.path.join(args.outdir, f"mgg_postcut_m{ref_mp}.pdf"))
        plt.close()
        print(f"[Figure 5b Generated] Saved {out_post}")


if __name__ == "__main__":
    main()
